seo:
  site_name: Bob, the VA
  title: Default SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark-text_color: 
  medium-text_color:
  light-text_color: 
  featured-text_color: 
  dark_color: 
  medium_color: 
  light_color: 
  v-light_color: 
  featured_color: 

